platform :ios, '12.0'
use_frameworks!

target 'GameApp' do
  # Add your dependencies here
  pod 'SDWebImage'
  # Add the Firebase pod for Google Analytics
  #  pod 'FirebaseAnalytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'SwiftKeychainWrapper'

end
